### ISSUE TITLE
Can't redefine a `nil` valued variable

### ISSUE THREAD

**Issue by mateodif** [Zelex/jo_clojure#11]
**Describe the bug**
I'm unable to redefine a variable whose value is `nil`.

**To Reproduce**
Hop into the REPL and do the following:
```
> (def foo nil)
> (def foo 123)
def: expected symbol
nil> (println foo)
nil
```

**Expected behavior**
`foo` should have the new value `123`. 
For reference, the proper behavior in a Clojure REPL:
```
user=> (def foo nil)
#'user/foo
user=> (def foo 123)
#'user/foo
user=> foo
123
```

**Comment by Zelex** [comment]
good catch, will fix

**Comment by Zelex** [comment]
Fixed
