### ISSUE TITLE
Feature request: REPL

### ISSUE THREAD

**Issue by mateodif** [Zelex/jo_clojure#8]
Are there any plans to eventually add a REPL?
It could be possible to integrate this project with [Cling](https://github.com/root-project/cling).

**Comment by Zelex** [comment]
Yeah I could do that. Haven't yet had a need for it personally.

**Comment by mateodif** [comment]
To me, it seems like a very crucial feature of Clojure. I'm glad that it could be worked on in the future! :)

**Comment by Zelex** [comment]
Implemented
